name: Build and push tg-bot-docsgpt-extenstion Docker image

on:
  push:
    branches:
      - main # Trigger on push to main branch

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-latest
            suffix: amd64
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
            suffix: arm64
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU  # Only needed for emulation, not for native arm64 builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push platform-specific images
        uses: docker/build-push-action@v6
        with:
          file: './Dockerfile'
          platforms: ${{ matrix.platform }}
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/tg-bot-docsgpt-extenstion:latest-${{ matrix.suffix }}
            ghcr.io/${{ github.repository_owner }}/tg-bot-docsgpt-extenstion:latest-${{ matrix.suffix }}
          provenance: false
          sbom: false
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/tg-bot-docsgpt-extenstion:latest
          cache-to: type=inline

  manifest:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifest for DockerHub
        run: |
          set -e
          docker manifest create ${{ secrets.DOCKER_USERNAME }}/tg-bot-docsgpt-extenstion:latest \
            --amend ${{ secrets.DOCKER_USERNAME }}/tg-bot-docsgpt-extenstion:latest-amd64 \
            --amend ${{ secrets.DOCKER_USERNAME }}/tg-bot-docsgpt-extenstion:latest-arm64
          docker manifest push ${{ secrets.DOCKER_USERNAME }}/tg-bot-docsgpt-extenstion:latest

      - name: Create and push manifest for ghcr.io
        run: |
          set -e
          docker manifest create ghcr.io/${{ github.repository_owner }}/tg-bot-docsgpt-extenstion:latest \
            --amend ghcr.io/${{ github.repository_owner }}/tg-bot-docsgpt-extenstion:latest-amd64 \
            --amend ghcr.io/${{ github.repository_owner }}/tg-bot-docsgpt-extenstion:latest-arm64
          docker manifest push ghcr.io/${{ github.repository_owner }}/tg-bot-docsgpt-extenstion:latest